program : declaration*

// Comandos
?declaration : var_decl
             // | class_decl
             // | fun_decl
             | statement

// class_decl : "class" IDENTIFIER [ "<" IDENTIFIER ] "{" function* "}"
// fun_decl   : "fun" function
var_decl   : "var" IDENTIFIER [ "=" expression ] ";"

?statement : print_stmt
           | while_stmt
           // | if_stmt
           // | for_stmt
           // | expr_stmt
           | block
           | expression_stmt

while_stmt : "while" "(" expression ")" statement

block : "{" declaration* "}"

print_stmt : "print" expression ";"

expression_stmt : expression ";"

// Expressões
?expression : assignment

?assignment : IDENTIFIER "=" assignment
            | cmp

?cmp : cmp ">" math  -> gt
     | cmp "<" math  -> lt
     | cmp "<=" math -> le
     | cmp ">=" math -> lt
     | cmp "==" math -> eq
     | cmp "!=" math -> ne
     | math

?math : math "+" term -> add
      | math "-" term -> sub
      | term

?term : term "*" pow -> mul
      | term "/" pow -> div
      | pow

?pow  : atom "^" pow -> pow
      | atom

atom : STRING | NUMBER | IDENTIFIER | "true" | "false" | "nil"

COMMENT    : /\/\/[^\n]*/
WS         : /\s+/
IDENTIFIER : /[a-zA-Z_][a-zA-Z_0-9]*/
STRING     : /"[^"]*"/
NUMBER     : /[0-9]+(\.[0-9]+)?/

%ignore WS | COMMENT